### ISSUE TITLE
Unit of measurement for wind speed should be m/s but it is km/h in the card

### ISSUE THREAD

**Issue by damiano75** [clayauld/lovelace-darksky-card#1]
**Describe the bug**
Unit of measurement for wind speed should be m/s but it is km/h in the card

**Screenshots**
Here some screenshots

![image](https://user-images.githubusercontent.com/47896789/82657801-45164880-9c26-11ea-9472-06b2a15449d9.png)

![image](https://user-images.githubusercontent.com/47896789/82658925-21540200-9c28-11ea-8212-1fd6355c66f6.png)

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Browser Edge
 - Version 81.0.416.77
 - Browser Chrome
 - Version 83.0.4103.61
 - etc.

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: 13.5
 - HA app

**Comment by clayauld** [comment]
Can you post what you have put in your card configuration?

**Comment by clayauld** [comment]
This is a duplicate issue of https://github.com/iammexx/home-assistant-config/issues/23.

**Comment by cyposk** [comment]
@damiano75 
Edit file lovelace-darksky-card.js
Line 322
add " * 3.6 "
var windSpeed = this.config.entity_wind_speed ? Math.round(this._hass.states[this.config.entity_wind_speed].state * 3.6 ) : 0;

**Comment by clayauld** [comment]
New update should fix this issue.
