### ISSUE TITLE
popups not working

### ISSUE THREAD

**Issue by jscherry** [clayauld/lovelace-darksky-card#2]
**Describe the bug**
I have copied all the files to the proper directories including the static and animated icons and none of the icons are showing up after creating the card. I am not seeing the popups shown on the example? If I have the wrong location for this comment sorry. Can you please let me know what I could have wrong or the proper place to ask for help? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jlverhagen** [comment]
Double check that you created the _weather_icons_ directory inside the _www/icons_ directory and not in the _www/images/icons_ directory. I made that mistake. Also check if the directories and files you created or copied are accessible to the user account that Home Assistant runs under. You may need to change the permissions or ownership of the directories and files so Home Assistant can access them, if you created the new directories and files under a different user account.

For the popups (tooltips), you can enable them by adding:

`tooltips: true`

to the lovelace-darksky-card card configuration in the lovelace ui.

**Comment by jscherry** [comment]
Got it fixed. I had the icons folder names wrong. Thanks
